### ISSUE TITLE
Latency analysis of transaction effects ingestion

### ISSUE THREAD

**Issue by kodemartin** [iotaledger/iota#3239]
## Description

We are primarily interested on the latency between the execution of a transaction in the node and the persistence of its effects on the indexer database.

It might be interesting exploring and collecting all the latency metrics supported by the indexer through its internal `metrics`.  Using a grafana dashboard to visualize all metrics would come handy. 

### References for grafana deployment

* https://github.com/iotaledger/iota/tree/develop/docker/grafana-local

**Comment by tomxey** [comment]
## Initial measurements:

All times provided here are average times from 100 or more tx executions.
The order of events is not fixed, in some cases it may happen that e.g. checkpoint is already created at the time indexer client gets response from the indexer.

### Relative timestamps of events:
Indexer client gets successful response from indexer: 0 ms
Checkpoint with executed tx gets created by the fullnode (according to checkpoint timestamp): 121.99 ms
Checkpoint gets fetched by the indexer: 366.64 ms
Checkpoint gets committed to indexer db: 433.49 ms
Indexer client is able to see tx effects via indexer api: 454.90 ms

So the total waiting time to see the effects by the indexer client is **454.90 ms**

### Durations:
Waiting for the checkpoint: 121.99 ms
Waiting for checkpoint to be fetched by indexer: 244.65 ms
Indexation duration: 66.85 ms


### Conclusions:

The biggest amount of time is spent waiting for checkpoint to be fetched by the indexer. I'll try to investigate what is the reason.

**Comment by kodemartin** [comment]
Discussion on possible options for treating the problem in [Sui RPC2.0 design announcement](https://www.github.com/MystenLabs/sui/issues/13700#issuecomment-1763537758)

> > > Data Consistency
> > > To enable this, the RPC’s indexer will need to commit writes as a result of checkpoint post-processing atomically, which increases latency (transactions that are final may take longer to show up in fullnode responses)
> >
> > How does this work then with read-after-write consistency where I'm committing a transaction and then trying to read it? Will I have to wait for the checkpoint to get committed before I can issue a consistent read?
>
> There's two ways to approach this -- the first is just to wait for the checkpoint which is the simplest option but will decrease your throughput by introducing checkpoint propagation and indexer post-processing to your critical path. This may not be so bad if your transactions involve shared objects because they need to go through consensus and appear in a checkpoint to be final anyway.
>
> The second option is to maintain the state you want locally, instead of relying on subsequent reads from the RPC. This approach is more complicated, but may be worthwhile if your transactions are otherwise operating in the single-owner fast path, and you care about your throughput. Typically what is important here is to know what the latest version of your owned objects are after having run some prior transactions on them, and this (the lamport version of a transaction accessing an owned object) is quite straightforward to forecast locally.
>
> While not in the immediate plans, we have discussed adding to our SDKs to do this automatically for you (i.e. the SDK keeps track of the owned objects you use in your transactions, and the versions they went in as and came out as, acting as a cache to avoid having to read versions from RPC in your critical path).

I don't know if the second options is already implemented, but this is something that can be implemented on the server side as well. 

cc: @lzpap, @begonaalvarezd
