### ISSUE TITLE
[move-ide] Publish the IOTA Move VSCode extension

### ISSUE THREAD

**Issue by miker83z** [iotaledger/iota#3710]

**Comment by valeriyr** [comment]
The extension can be published by following the official guide:
https://code.visualstudio.com/api/working-with-extensions/publishing-extension

Also, it is necessary to check if we need to change the manifest [__metadata](https://github.com/iotaledger/iota/blob/8f82d05d29811e4829effffce13d9224a48fb6c0/external-crates/move/crates/move-analyzer/editors/code/package.json#L182-L187) part:
```json
"__metadata": {
    "id": "71e74fc8-23c2-47b7-8594-ed00192d96a6",
    "publisherDisplayName": "move",
    "publisherId": "40d7def1-c662-4965-9ead-c06109c7cc6d",
    "isPreReleaseVersion": false
}
```
This section is the same in [Sui](https://github.com/MystenLabs/sui/blob/69d3653419174917d8ffe667f230609970f9a544/external-crates/move/crates/move-analyzer/editors/code/package.json#L182-L187) and [movebit/aptos-move-analyzer](https://github.com/movebit/aptos-move-analyzer/blob/542fa4d8a6b84aa8307e96bf30a0499be93da7d9/editors/code/package.json#L225-L230), for example.

I changed `id` and `publisherId` on randomly generated UUIDs [here](https://github.com/iotaledger/iota/pull/3310). The `publisherDisplayName` also was changed.
