### ISSUE TITLE
[iota-replay] Re-evaluate/re-enable ignored tests after testnet launch

### ISSUE THREAD

**Issue by miker83z** [iotaledger/iota#3833]
- [x] verify_latest_tx_replay_testnet_mainnet 
- [x] test_profiler 
- [ ] test_unwind 
- [ ] test_end_to_end 
- [x] replay_sandboxes (covered by #1499)
- [x] nested_deps_git_local (covered by #3111)

**Comment by Dkwcs** [comment]
`verify_latest_tx_replay_testnet_mainnet` should be postponed because of mainnet absence

**Comment by Dkwcs** [comment]
`nested_deps_git_local` passes with `cargo nextest run nested_deps_git_local/Move.toml`

**Comment by Dkwcs** [comment]
`test_unwind` skipping due to external crates location

**Comment by thibault-martinez** [comment]
> `nested_deps_git_local` passes with `cargo nextest run nested_deps_git_local/Move.toml`

Can we close https://github.com/iotaledger/iota/issues/3111 then?

**Comment by Dkwcs** [comment]
> > `nested_deps_git_local` passes with `cargo nextest run nested_deps_git_local/Move.toml`
> 
> Can we close [#3111](https://github.com/iotaledger/iota/issues/3111) then?

I think so

**Comment by Dkwcs** [comment]
`test_end_to_end` fails with an error - `No upgrade transaction observed`.

I guess the problem is the `watch_for_upgrades` function that looks unusable.
```
pub async fn watch_for_upgrades(
    _packages: Vec<PackageSource>,
    _app_state: Arc<RwLock<AppState>>,
    _network: Network,
    _channel: Option<Sender<SuiTransactionBlockEffects>>,
) -> anyhow::Result<()> {
    Err(anyhow!("Fatal: JsonRPC Subscriptions no longer supported. Reimplement without using subscriptions.”))
}
```
So we can postpone test enabling.

**Comment by thibault-martinez** [comment]
> ```
> pub async fn watch_for_upgrades(
>     _packages: Vec<PackageSource>,
>     _app_state: Arc<RwLock<AppState>>,
>     _network: Network,
>     _channel: Option<Sender<SuiTransactionBlockEffects>>,
> ) -> anyhow::Result<()> {
>     Err(anyhow!("Fatal: JsonRPC Subscriptions no longer supported. Reimplement without using subscriptions.”))
> }
> ```

Is that a function we should remove while we still have a chance?

**Comment by Dkwcs** [comment]
> > ```
> > pub async fn watch_for_upgrades(
> >     _packages: Vec<PackageSource>,
> >     _app_state: Arc<RwLock<AppState>>,
> >     _network: Network,
> >     _channel: Option<Sender<SuiTransactionBlockEffects>>,
> > ) -> anyhow::Result<()> {
> >     Err(anyhow!("Fatal: JsonRPC Subscriptions no longer supported. Reimplement without using subscriptions.”))
> > }
> > ```
> 
> Is that a function we should remove while we still have a chance?

I guess we can do it in scope of `test_end_to_end` further fixing.
Because maybe we can refactor this function without removing.

**Comment by miker83z** [comment]
Continues in #4448
