### ISSUE TITLE
Add kiosks predefined rules packages

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/iota#3904]
Add deployed packages in Mainnet and Testnet to .env.defaults and all necessary environment variables for the TS SDK
Read https://github.com/iotaledger/iota/issues/3858#issuecomment-2455242279 for more information about the topic

Blocked until packages are not provided --> package with all rules `0x975f749f57701209454e4b9b9e33825ccb6a9abf57de2ce86979e5fa86c343f2`

**Comment by miker83z** [comment]
@begonaalvarezd @cpl121 
On the Testnet the package id is: [0x975f749f57701209454e4b9b9e33825ccb6a9abf57de2ce86979e5fa86c343f2](https://explorer.rebased.iota.org/object/0x975f749f57701209454e4b9b9e33825ccb6a9abf57de2ce86979e5fa86c343f2)

Do we need it also on the Devnet, or is it fine just this for the SDK? 

(tracking issue #3982)

**Comment by begonaalvarezd** [comment]
> [@begonaalvarezd](https://github.com/begonaalvarezd) [@cpl121](https://github.com/cpl121) On the Testnet the package id is: [0x975f749f57701209454e4b9b9e33825ccb6a9abf57de2ce86979e5fa86c343f2](https://explorer.rebased.iota.org/object/0x975f749f57701209454e4b9b9e33825ccb6a9abf57de2ce86979e5fa86c343f2)
> 
> Do we need it also on the Devnet, or is it fine just this for the SDK?
> 
> (tracking issue [#3982](https://github.com/iotaledger/iota/issues/3982))

I think Testnet for now should be enough yes, since Testnet is not intended to be reset thats enough. Later on we will need for mainnet too
