### ISSUE TITLE
Fix logo/avatar/icon image, move to core and cleanup debris

### ISSUE THREAD

**Issue by cpl121** [iotaledger/iota#3939]
Refactor everything related to icons, avatars, or whatever they're called, to ensure consistent icons across all the apps, move to core folder and cleanup all debris across the apps

Example:
![Image](https://github.com/user-attachments/assets/462fa509-00a5-4589-983e-ba86aeab04fd)

**Comment by begonaalvarezd** [comment]
Waiting for https://github.com/iotaledger/iota/issues/3687
