### ISSUE TITLE
Cleanup docs of new IOTA CLI commands

### ISSUE THREAD

**Issue by lzpap** [iotaledger/iota#3951]
The new CLI commands' docs need to be polished.

**Comment by thibault-martinez** [comment]
Didn't know, just remembered I saw some more when I rebased so I just checked now:
- [x] IotaValidatorCommand::RegisterBridgeCommittee
- [x] IotaValidatorCommand::UpdateBridgeCommitteeNodeUrl
- [ ] IotaCommand::BridgeInitialize (TBD in https://github.com/iotaledger/iota/issues/4175)
- [ ] IotaCommand::Analyzer (TBD in https://github.com/iotaledger/iota/issues/4175)
