### ISSUE TITLE
[Task (tooling/explorer)]: use in the explorer ImageIcon component from `@iota/core`

### ISSUE THREAD

**Issue by panteleymonchuk** [iotaledger/iota#3969]
### Context

The ImageIcon component, originally implemented in the wallet, has been relocated to the @iota/core library to standardize usage across all IOTA applications. To improve maintainability and avoid code duplication, we should now replace existing instances of ImageIcon in other applications (such as explorer) with the version from @iota/core.

### Description of Task

Align and integrate the ImageIcon component from @iota/core into the explorer. This will ensure consistent usage of the component across all applications, streamlining updates and reducing redundancy in component implementation.

### DoD:
- [ ] Review the `ImageIcon` component implementation in `explorer` and compare it with the version in `@iota/core`. Ensure feature parity and visual consistency.
- [ ] Replace all instances of `ImageIcon` in `explorer` with the `@iota/core` version.
- [ ] Test to confirm that the replacement functions correctly in all scenarios where `ImageIcon` is used within `explorer`.

### Related issues:
- https://github.com/iotaledger/iota/issues/3916
- https://github.com/iotaledger/iota/pull/3832#discussion_r1832309909
- https://github.com/iotaledger/iota/pull/3917

**Comment by evavirseda** [comment]
Closed in favor of https://github.com/iotaledger/iota/issues/3939
