### ISSUE TITLE
`--coverage` flag in the CLI

### ISSUE THREAD

**Issue by salaheldinsoliman** [iotaledger/iota#4035]
## Description
Related to #1417 

When trying test coverage feature, it requires the dev to build `iota` from source with `debug` mode:
`iota move test --coverage
The --coverage flag is currently supported only in debug builds. Please build the Iota CLI from source in debug mode.`

Why is this not enabled by default? and why does it need another version of the CLI?

**Comment by thibault-martinez** [comment]
Closing this as there is not much we can do. `move test/coverage` is a debug feature that requires a debug build.
