### ISSUE TITLE
Request for`--with-example` flag for `iota move new`

### ISSUE THREAD

**Issue by salaheldinsoliman** [iotaledger/iota#4039]
## Description
Is it a good idea to have a `--with-example` flag added to the iota move new command, which enables a dev to start right away with one of the examples in https://github.com/iotaledger/iota/tree/develop/examples/move ?
Something like this: `iota move new --with-example flash_lender` , with a default of first_package maybe.

Related to #1417

**Comment by salaheldinsoliman** [comment]
Github interface doesn't provide a direct way to download one directory, one has to clone the entire dir and copy it, or use a 3rd part tool: https://stackoverflow.com/questions/7106012/download-a-single-folder-or-directory-from-a-github-repository
That is why I think it provides a slightly better experience.

**Comment by thibault-martinez** [comment]
After internal discussions, we think this is maybe too fine-grained to be added to the CLI. It shouldn't be too annoying for a developer to clone the repository and copy the relevant folder.
