### ISSUE TITLE
Add darkmode support: Epoch page

### ISSUE THREAD

**Issue by VmMad** [iotaledger/iota#4073]
1. Number and legends in the radial graph are only lightmode
2. Progressbar should have inverted colors
3. Validators table is only lightmode (not using panel?)
4. Buttons and pagination are missing darkmode colors.
5. Panels in epoch page have different colors (should be a darker color)

**Comment by evavirseda** [comment]
_Panels in epoch page have different colors (should be a darker color)_

This is going to be updated in other [PR](https://github.com/iotaledger/iota/pull/4140) because all panels have wrong darkmode
