### ISSUE TITLE
Estimated gas fee mismatch between wallet & wallet dashboard

### ISSUE THREAD

**Issue by panteleymonchuk** [iotaledger/iota#4081]
Repro steps: wallet-dashboard > stake > enter amount view.

In the "Gas" column it shows  value. In the wallet and after execute transaction the gas value is different.

Expected result: to see on the screen same value as in the wallet.

Issue found after work with https://github.com/iotaledger/iota/pull/3832

![Image](https://github.com/user-attachments/assets/f175eacc-eeb3-4c98-bc7b-d9205f242c0a)
![Image](https://github.com/user-attachments/assets/c4d4634f-95bf-4fe0-8260-0e01453abbe1)

**Comment by begonaalvarezd** [comment]
We've investigated this topic and we will proceed as follows:
- we will update all the transaction building (except staking) to do a dry run to get the real gas fee that will be used
- as for staking, we will keep the logic of dry running for the final staking amount and just building for estimating the gas budget to deduct it from the total amount

With these changes, we can display the gas fee to the user so its really the estimated gas fee and not the budget, the budget includes an overhead we dont have to display

This issue can be closed as the solution will be tackled in future issues, which first will need to be preceeded by a refactor on the hooks we use in the wallet and the dashboard to unify the logics and dry run accordingly
