### ISSUE TITLE
Can not find a public available node.

### ISSUE THREAD

**Issue by sunshengjing** [iotaledger/iota#4157]
## Description
I am working on a iota project, try to publish data to Iota tangle. 4 years ago I was using the url [https://nodes.devnet.iota.org], it worked well. 

However, now I am using the same url, it returns [bad gateway or access failed]. I also tried to find more public nodes at https://iota-nodes.net/, the url is not working anymore either.

Can you share with me some public nodes?

Many thanks.

Shengjing

**Comment by Thoralf-M** [comment]
There were breaking changes since then, so your code will not work with any running node anymore.
For nodes that are compatible with the code in this repository you can find the endpoints here: https://docs.iota.org/developer/network-overview
