### ISSUE TITLE
Upgrade rust toolchain to 1.82

### ISSUE THREAD

**Issue by muXxer** [iotaledger/iota#4165]
Currently the release-v0.7.0 docker containers are build with the latest stable rust version, which is 1.82 at this point in time.
This is due to the fact that we are using the `rust:latest` images in the build step, and because we don't copy the `rust-toolchain.toml` with the actual used toolchain version into the containers. This will be fixed with #4044 

Nevertheless we should upgrade the used rust toolchain version to the latest released stable version of rust.
This should be done after #3705 is merged to develop.

**Comment by gsimsekfb** [comment]
@muXxer I started with my local, upgraded `iota/rust-toolchain.toml` to 1.82 and running `cargo clippy`. Will run `RUSTFLAGS="--cfg msim" cargo clippy` next. 

Tried to find how exactly we run clippy, I am guessing this is the place: https://github.com/iotaledger/iota/blob/391a28bf51bd9ac1ca7ea3f516a8a755a9951315/scripts/slipstream/slipstream.py#L609C1-L612C72 -> `# Run cargo clippy
def run_cargo_clippy(panic_on_errors): ` 

Opening a PR like this https://github.com/iotaledger/iota/pull/3705 to trigger the CI might be also an option or run CI scripts locally.

**Comment by gokhan-simsek-iota** [comment]
@muXxer I started with my local, upgraded `iota/rust-toolchain.toml` to 1.82 and running `cargo clippy`. Will run `RUSTFLAGS="--cfg msim" cargo clippy` next. 

Tried to find how exactly we run clippy, I am guessing this is the place: https://github.com/iotaledger/iota/blob/391a28bf51bd9ac1ca7ea3f516a8a755a9951315/scripts/slipstream/slipstream.py#L609C1-L612C72 -> `# Run cargo clippy
def run_cargo_clippy(panic_on_errors): ` 

Opening a PR like this https://github.com/iotaledger/iota/pull/3705 to trigger the CI might be also an option or run CI scripts locally to understand the whole process.

**Comment by thibault-martinez** [comment]
> Tried to find how exactly we run clippy

FYI in https://github.com/iotaledger/iota/pull/4180 we are introducing a new clippy job for msim.

**Comment by gokhan-simsek-iota** [comment]
This task is being done here https://github.com/iotaledger/iota/pull/4235

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota/pull/4235
