### ISSUE TITLE
Refactor: split iota-transaction-builder into multiple files

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota#4170]
## Description

Split [lib.rs](https://github.com/iotaledger/iota/blob/develop/crates/iota-transaction-builder/src/lib.rs) in iota-transaction-builder into multiple files

## Motivation

Better overview if it's not just one large file and logically separated

## Requirements

1. Move request_add_stake(), request_withdraw_stake(), request_add_timelocked_stake(),  request_withdraw_timelocked_stake() in a `stake.rs` file
2. Move select_gas(), get_object_arg(), input_refs(), resolve_and_checks_json_args(), get_object_ref(), get_object_ref_and_type() in a `utils.rs` file
3. Move publish_tx_kind(), publish(), upgrade_tx_kind(), upgrade() in a `package.rs` file

## Open questions (optional)

Anyone has better suggestions for the file names?

## Are you planning to do it yourself in a pull request?

No.

**Comment by sarahagib** [comment]
Hi, my name is Sarah and I am an engineering student looking for a good first issue. If no one is already working on this issue, I would like to be assigned.

**Comment by thibault-martinez** [comment]
> Hi, my name is Sarah and I am an engineering student looking for a good first issue. If no one is already working on this issue, I would like to be assigned.

Hi Sarah, it's yours! Thanks :)
