### ISSUE TITLE
[Bug (tooling/wallet-dashboard)]: Alert "insufficient funds" shows when open staking with 0 balance.

### ISSUE THREAD

**Issue by panteleymonchuk** [iotaledger/iota#4195]
Issue found by @VmMad 

This message popped up when user with 0 balance open the page and didn't click anything.
in the wallet the same issue, but user can’t go to the stake page if balance is zero

![Image](https://github.com/user-attachments/assets/05e14062-d180-4890-aa91-6c0ced06c24c)

**Comment by begonaalvarezd** [comment]
Superseeded by https://github.com/iotaledger/iota/issues/4418
