### ISSUE TITLE
[move-ide] Create an IOTA VS Code Extension Marketplace publisher

### ISSUE THREAD

**Issue by valeriyr** [iotaledger/iota#4241]
To publish the VS Code IOTA Move extension we need to create an account on the marketplace:
https://code.visualstudio.com/api/working-with-extensions/publishing-extension

Also, we need to create a publisher which will be reflected in the extension [manifest](https://github.com/iotaledger/iota/blob/8f82d05d29811e4829effffce13d9224a48fb6c0/external-crates/move/crates/move-analyzer/editors/code/package.json#L5):
https://code.visualstudio.com/api/working-with-extensions/publishing-extension#create-a-publisher

If we use `vsce` for the extension publishing, using CI, for example, we need to create a Personal Access Token:
https://code.visualstudio.com/api/working-with-extensions/publishing-extension#get-a-personal-access-token

**Comment by junwei0117** [comment]
The publisher has been created.
```
# vsce login iotaledger
 WARNING  Failed to open credential store. Falling back to storing secrets clear-text in: /root/.vsce
https://marketplace.visualstudio.com/manage/publishers/
Personal Access Token for publisher 'iotaledger': ************************************************************************************

The Personal Access Token verification succeeded for the publisher 'iotaledger'.
```

**Comment by valeriyr** [comment]
@junwei0117 thank you! As I see we should change the published name in the extension manifest to `iotaledger`. Because now it is set to `iota-foundation`.
