### ISSUE TITLE
Create and add VS_MARKETPLACE_TOKEN for Move VS Code extension

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota#4287]
## Description

Create a Personal Access Token that can be used to publish vs code extensions and add it to the repository secrets as `VS_MARKETPLACE_TOKEN`:
https://code.visualstudio.com/api/working-with-extensions/publishing-extension#get-a-personal-access-token

## Motivation

Allow us to publish the Move VS Code Extension

**Comment by junwei0117** [comment]
Done

![Image](https://github.com/user-attachments/assets/7adc97ce-2306-4c8e-991d-b0d8ecfd134d)
