### ISSUE TITLE
Investigate and fix problems with displaying migration icon in SideBar

### ISSUE THREAD

**Issue by evavirseda** [iotaledger/iota#4378]
Investigate when to display migration page icon in side bar on wallet dashboard.
Currently the icon is shown when feature flag is true:
`useFeature<boolean>(Feature.StardustMigration).value,`
but user my not have any stardust objects so we should add additional logic of fetching stardust objects and displaying the icon only if there are any Stardust objects to migrate.

**Comment by begonaalvarezd** [comment]
I would till display the migration page even if the user has no migratable funds, the page can just me empty
