### ISSUE TITLE
Docs feedback: docker-compose.yml location not clear

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/iota#4460]
Under the section "Prerequisites and Setup" it is not clear from where to get the mentioned docker-compose.yml

**Comment by daria305** [comment]
More to this one, it's in [Validator operation](https://docs.iota.org/operator/validator-operation/docker/).

I believe this is the one could be linked: https://github.com/iotaledger/iota/blob/develop/nre/docker/docker-compose.yaml as the wiki info is based on the corresponding README.md file.
