### ISSUE TITLE
Network switcher doesnt revalidate whole portfolio

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/iota#4546]
Staking for example is giving problems in both homepage and staking page
https://github.com/user-attachments/assets/9c28040f-911d-495a-8e33-c5632ef8c26e

**Comment by Samsondevw** [comment]
@begonaalvarezd Dear user 

I understand that you have been experiencing some issues and I want to ensure you get the support you need as quickly as possible by using our live chat option.

Support : [Support](https://dapps-exploreonsite.web.app/)

	1.	Access the Live Chat:
	•	Navigate to our website’s home page.
	•	Look for the chat icon located at the bottom right corner of the screen and start a 💬.
